// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mock

import (
	domain "discount-calculator/domain"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// FindOne provides a mock function with given fields: id
func (_m *Repository) FindOne(id string) (domain.Product, error) {
	ret := _m.Called(id)

	var r0 domain.Product
	if rf, ok := ret.Get(0).(func(string) domain.Product); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
