// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"discount-calculator/api/rpc/server"
	"discount-calculator/infrastructure/repository"
	"discount-calculator/internal/mongodb"
	"discount-calculator/pkg"
	"discount-calculator/usecase/discount"
	"discount-calculator/usecase/product"
	"discount-calculator/usecase/user"
)

// Injectors from wire.go:

func SetupApplication() pkg.Application {
	listener := pkg.NewListener()
	server := pkg.NewGrpcServer()
	client := mongodb.NewMongoClient()
	productRepository := repository.NewProductRepository(client)
	service := product.NewService(productRepository)
	userRepository := repository.NewUserRepository(client)
	userService := user.NewService(userRepository)
	discountService := discount.NewService(service, userService)
	apiServer := api.NewServer(discountService, server)
	application := pkg.Application{
		Listener: listener,
		Server:   server,
		RpcImpl:  apiServer,
	}
	return application
}
